/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "director_constants.h"

namespace xspace { namespace director {

const directorConstants g_director_constants;

directorConstants::directorConstants() {
}

}} // namespace

