/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef director_CONSTANTS_H
#define director_CONSTANTS_H

#include "director_types.h"

namespace xspace { namespace director {

class directorConstants {
 public:
  directorConstants();

};

extern const directorConstants g_director_constants;

}} // namespace

#endif
