// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "SpaceService.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace xspace::director;

class SpaceServiceHandler : virtual public SpaceServiceIf {
 public:
  SpaceServiceHandler() {
    // Your initialization goes here
  }

  bool Setup(const std::string& name, const std::string& passwd) {
    // Your implementation goes here
    printf("Setup\n");
  }

  void Close() {
    // Your implementation goes here
    printf("Close\n");
  }

  void GetSpaceInfo(SpaceInfoRsp& _return, const std::string& space) {
    // Your implementation goes here
    printf("GetSpaceInfo\n");
  }

  void GetSpaceList(SpaceListRsp& _return) {
    // Your implementation goes here
    printf("GetSpaceList\n");
  }

  bool CreateSpace(const std::string& space, const SpaceType::type type) {
    // Your implementation goes here
    printf("CreateSpace\n");
  }

  bool DeleteSpace(const std::string& space) {
    // Your implementation goes here
    printf("DeleteSpace\n");
  }

  bool RenameSpace(const std::string& oldspace, const std::string& newspace) {
    // Your implementation goes here
    printf("RenameSpace\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<SpaceServiceHandler> handler(new SpaceServiceHandler());
  shared_ptr<TProcessor> processor(new SpaceServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

